#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=01
start_service() {
    mkdir /tmp/blockp2p 2>/dev/null
    procd_open_instance
    procd_set_param command /usr/bin/blockp2p
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    cat /dev/null > /tmp/iptables_sum
}

service_triggers()
{
    procd_add_reload_trigger "blockp2p"
}
